vim.keymap.set("n", "<C-A>", ":Sidekick cli show name=qwen<CR>")
vim.keymap.set("n", "=", [[<cmd>vertical resize +5<cr>]])
vim.keymap.set("n", "-", [[<cmd>vertical resize -5<cr>]])
vim.keymap.set("n", "+", [[<cmd>horizontal resize +2<cr>]])
vim.keymap.set("n", "_", [[<cmd>horizontal resize -2<cr>]])
vim.keymap.set("v", "<C-y>", function() require("nvim-silicon").clip() end, { noremap = true, silent = true })
